### ISSUE TITLE
[Locale] Arabic support

### ISSUE THREAD

**Issue by Mohammad-Ha** [runkids/vue2-timeago#1]
export default {
short: {
                now: "قبل قليل",
                sec: " ثانية",
                min: " دقيقة",
                hour: " ساعة",
                day: " يوم"
            },
            long: {
                now: "قبل قليل",
                sec: " ثواني مضت",
                min: " دقائق مضت",
                hour: " ساعات مضت",
                day: " أيام مضت"
            }
}

Please note that we don't have the same as English. This means that instead of **5 minutes ago**, we write **before 5 minutes**

There fore, if you can replace the $value with the time-left, it would be better. Otherwise, you can use the first list, which doesn't require you to reorder the logic of your code. The first list above uses the same as English. I prefer the second one.

Also, there's a difference between singular and plural. If you could implement this, please let me know so i can give you a better translation.

export default {
short: {
                now: "قبل قليل",
                sec: " ثانية",
                min: " دقيقة",
                hour: " ساعة",
                day: " يوم"
            },
            long: {
                now: "قبل قليل",
                sec: " قبل $time ثواني",
                min: " قبل $time دقائق",
                hour: " قبل $time ساعات",
                day: " قبل $time أيام"
            }
}

**Comment by runkids** [comment]
Thank you for your feedback. I will use your feedback for future improvement
