### ISSUE TITLE
Critical dependency

### ISSUE THREAD

**Issue by monstromatic** [runkids/vue2-timeago#3]
WARNING in ./node_modules/vue2-timeago/dist/vue2-timeago.js 1:294-298
Critical dependency: the request of a dependency is an expression

Any idea how to fix that?

**Comment by ralphjesy12** [comment]
Same issue. Any update?

**Comment by acamenhas** [comment]
Same here

**Comment by runkids** [comment]
Hi, can you try v2 version again? Thank you.
