### ISSUE TITLE
How it is related to vue-timeago from egoist

### ISSUE THREAD

**Issue by gustawdaniel** [runkids/vue2-timeago#39]
There is about 10x more popular package: `vue-timeago` created by `egoist`.

https://www.npmjs.com/package/vue-timeago

but now this repository is archived

https://github.com/egoist/vue-timeago

+ Do you know why?
+ Is this package inspired by `vue-timeago`, or totally other concept under the hood?

**Comment by runkids** [comment]
Hi gustawdaniel, about your questions.

- Do you know why?
Sorry, I don't know why. 😅

- Is this package inspired by vue-timeago, or totally other concept under the hood?
No, I started to learning Vue three years ago and this project was inspired by one example in this book. 😁
![730248492](https://user-images.githubusercontent.com/15520254/127735729-1d8d2f1f-e71a-4761-9e3b-58684ae46236.jpeg)

I will close this issue. if you have any questions keep comments on this issue, thanks!

**Comment by gustawdaniel** [comment]
Thanks @runkids. I will migrate all my projects to use your package. Great job :D
